config/routes.rb
Forum::Application.routes.draw do

  
  root   'topics#index'


  devise_for :users


  resources :topics, except: [:show, :edit] do
    resources :user_threads, except: [:show, :edit] do
      resources :posts, except: [:show, :edit] do
        member do 
          patch 'mark-as-spam'  => 'posts#spam',      as: 'spam'
          patch 'rate-up'       => 'posts#rate_up',   as: 'rate_up'
          patch 'rate-down'     => 'posts#rate_down', as: 'rate_down'
        end
      end
    end
  end

  # Suche
  get     "search"                  => 'search#search'

  # Adminbereich
  get     "admin/index"            => 'admins#index',         as: :admins_index
  delete  "admin/destroy/:id"      => 'admins#destroy',       as: :admins_destroy
  patch   "admin/nospam/:id"       => 'admins#noSpam' ,       as: :admins_nospam
  get     "admin/new-posts"        => 'admins#new_posts',     as: :admin_new_posts
  get     "admin/spam-posts"       => 'admins#spam_post',     as: :admin_spam_posts
  get     "admin/topics-threads"   => 'admins#topics_threads',as: :admin_topics_threads
  get     "admin/users"            => 'admins#users',         as: :admin_users
  get     "admin/topics/:id/edit"  => 'admins#topic_edit',    as: :admin_edit_topic
  get     "admin/thread/:id/edit"  => 'admins#thread_edit',   as: :admin_edit_thread
  get     "admin/thread/:id/move"  => 'admins#thread_move',   as: :admin_move_thread
  patch   "admin/thread/:id/moved" => 'admins#thread_moved',  as: :admin_moved_thread

  # User
  get   "user"          => 'user#current_user_profil',          as: 'current_user'
  patch "user"          => 'user#update'
  put   "user"          => 'user#update'
  get   "user/edit"     => 'user#edit',                         as: 'edit_user'
  get   "user/threads"  => 'user#current_user_threads',         as: 'current_user_threads'
  get   "user/messages" => 'user#current_user_messages',        as: 'current_user_messages'
  get   "user/:id"      => 'user#show',                         as: 'show_user'

  # Private Nachrichten
  get   "user/messages/new-message" => 'private_message#new_message',           as: 'private_messages'
  post  "user/messages/new-message" => 'private_message#send_private_message'
  get   "user/messages/:id"         => 'private_message#show',                  as: 'show_private_message'

  # Statische Seiten
  get "/impressum" => "static_pages#impressum" , as: 'impressum'

end

app/views/admins/_menue.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation"">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand">Menue</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "Admin", admins_index_path %></li>
          <li><%= link_to "users", admin_users_path %></li>
          <li><%= link_to "topics & threads", admin_topics_threads_path %></li>
          <li><%= link_to "spam posts", admin_spam_posts_path %></li>
          <li><%= link_to "new posts", admin_new_posts_path %></li>
          <li><%= link_to "Forum", root_path %></li>
        </ul>
      </div>
</div>

app/views/admins/index.html.erb
<h1> Admin-Bereich </h1>

<table id = "statsTable" class="table table-hover">
  <tr>
    <td>Registrierte User</td>
    <td><%= User.all.count %></td>
  </tr>
  <tr>
    <td>In den letzten 24h registrierte User</td>
    <td><%= User.where("created_at > :day", { :day => 1.day.ago } ).count %></td>
  </tr>
  <tr>
    <td>Anzahl Posts</td>
    <td><%= Post.all.count %></td>
  </tr>
  <tr>
    <td>Anzahl spam Posts</td>
    <td><%= Post.where(:spam => true).count %></td>
  </tr>
  <tr>
    <td>Anzahl Topics</td>
    <td><%= Topic.all.count %></td>
  </tr>
  <tr>
    <td>Anzahl Threads</td>
    <td><%= UserThread.all.count %></td>
  </tr>
  <tr>
    <td>Anzahl private Nachrichten</td>
    <td><%= PrivateMessage.all.count %></td>
  </tr>
</table>

app/views/admins/new_posts.html.erb
<% @title = "Neuste Posts" %>
<h1>Neuste Posts</h1>

<table id = "postTable" class="table table-hover">
  <tr>
    <th>Post</th>
    <th>User</th>
    <th>Datum</th>
  </tr>
  <% @newPosts.each do |post| %>
      <% topic = post.user_thread.topic %>
      <% user_thread = post.user_thread %>
      <% user = post.user %>
      <tr>
        <td> <%= link_to post.title, path_to_post(post) %> </td>
        <td>
        <% unless user.nil? %>
         <%= link_to user.email, show_user_path(user) %> 
        <% else %>
        geloeschter User
        <% end %>
        </td>
        <td> <%= post.created_at %> </td>
      </tr>
  <%end%>
</table>

app/views/admins/spam_post.html.erb
<% @title = "Spam Posts" %>
<h1>Spam Posts</h1>

<table id = "spamTable" class="table table-hover">
  <tr>
    <th>Spampost</th>
    <th>Spam ?</th>
    <th></th>
  </tr>

  <% @posts.each do |post| %>
      <tr>
        <td> <%= link_to post.title, path_to_post(post) %> </td>
        <td> <%= link_to "Kein Spam", admins_nospam_path(post.id), method: :patch %> </td>
        <td>
          <%= link_to topic_user_thread_post_path(post.user_thread.topic, post.user_thread,post), method: "delete" do%>
              <span class="glyphicon glyphicon-remove-circle" title="Löschen"></span>
          <% end %>
        </td>
      </tr>
  <% end %>
</table>

app/views/admins/thread_edit.html.erb
<% @title = "Thread - Edit" %>
<h1>Edit-Thread</h1>

<%= render partial: 'layouts/error', locals: { errors: @user_thread.errors } %>

<%= form_for [@user_thread.topic, @user_thread], class: 'form-horizontal', html: { role: 'form', style: 'width: 25%'} do |f| %>
    <div class="form-group">
      <%= f.label :title, for: 'input-lable' %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <%= f.submit class: 'btn btn-success' %>
    <%= link_to "Abbrechen", admin_topics_threads_path, class: 'btn btn-danger' %>
<% end %>

app/views/admins/thread_move.html.erb
<h1> Verschieben </h1>

<%= form_tag admin_moved_thread_path(params[:id]), method: 'patch', html: {role: 'form', style: 'width: 20%'} do %>
    <div class="form-group">
        <%= label_tag(:to,"Verschieben nach: ") %>
        <%= collection_select(:user_thread, :topic, @options, :id, :name, class: 'form-control') %>
    </div>

    <%= submit_tag("Okay",class: "btn btn-success") %>
    <%= link_to "Abbrechen",admin_topics_threads_path,class: "btn btn-danger" %>
<% end %>

app/views/admins/topic_edit.html.erb
<% @title = "Topic - Edit" %>
<h1>Edit-Topic</h1>

<%= render partial: 'layouts/error', locals: { errors: @topic.errors } %>

<%= form_for @topic, class: 'form-horizontal', html: {role: 'form', style: 'width: 20%'} do |f| %>
    <div class="form-group">
      <%= f.label :name, class: 'control-label', for: 'input-lable' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <%= f.submit class: 'btn btn-success' %>
    <%= link_to 'Abbrechen', admin_topics_threads_path, class: 'btn btn-danger' %>
<% end %>

app/views/admins/topics_threads.html.erb
<% @title = "Topics & Threads" %>

<div class="row">
  <div class="col-xs-6">
    <h1>Topics</h1>

    <table id="topicTable" class="table table-hover">
      <tr>
        <th>Topic</th>
        <th>Anzahl Threads</th>
        <th></th>
      </tr>

      <% @topic.each do |topic| %>
          <tr>
            <td> <%= link_to topic.name, topic_user_threads_path(topic) %> </td>
            <td> <%= topic.user_threads.count %> </td>
            <td>
              <%= link_to topic_path(topic), method: :delete do %>
                  <span class="glyphicon glyphicon-remove-circle" title="Löschen"></span>
              <% end %>

              <%= link_to admin_edit_topic_path(topic) do %>
                  <span class="glyphicon glyphicon-pencil" title="Bearbeiten"></span>
              <% end %>
            </td>
          </tr>
      <% end %>
    </table>
  </div>

  <div class="col-xs-6">
    <h1>Threads</h1>

    <table id="threadTable" class="table table-hover">
      <tr>
        <th>Thread</th>
        <th>Anzahl Posts</th>
        <th></th>
        <th></th>
      </tr>

      <% @userThread.each do |thread| %>
          <tr>
            <td>
              <%= link_to thread.title, topic_user_thread_posts_path(thread.topic, thread) %>
            </td>

            <td> <%= thread.posts.count %> </td>

            <td></td>

            <td>
              <%= link_to topic_user_thread_path(thread.topic, thread), method: :delete do %>
                  <span class="glyphicon glyphicon-remove-circle" title="Löschen"></span>
              <% end %>

              <%= link_to admin_edit_thread_path(thread) do %>
                  <span class="glyphicon glyphicon-pencil" title="Bearbeiten"></span>
              <% end %>

              <%= link_to admin_move_thread_path(thread) do %>
                  <span class="glyphicon glyphicon-hand-right" title="Verschieben"></span>
              <% end %>
            </td>
          </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/admins/users.html.erb
<% @title = "Users" %>
<h1>Users</h1>

<table id = "userTable" class="table table-hover">
  <tr>
    <th>id</th>
    <th>User-Email</th>
    <th>Zuletzt eingeloggt</th>
    <th>Anzahl Posts</th>
    <th></th>
  </tr>
  <% @users.each do |user| %>
      <tr>
        <td> <%= user.id %> </td>
        <td> <%= link_to user.email, show_user_path(user) %> </td>
        <td> <%= user.last_sign_in_at %> </td>
        <td> <%= user.posts.count %> </td>
        <td>
          <%= link_to admins_destroy_path(user.id), method: :delete do %>
              <span class="glyphicon glyphicon-remove-circle" title="Löschen"></span>
          <% end %>
        </td>
      </tr>
  <% end %>
</table>