config/routes.rb
Forum::Application.routes.draw do

  
  root   'topics#index'


  devise_for :users


  resources :topics, except: [:show, :edit] do
    resources :user_threads, except: [:show, :edit] do
      resources :posts, except: [:show, :edit] do
        member do 
          patch 'mark-as-spam'  => 'posts#spam',      as: 'spam'
          patch 'rate-up'       => 'posts#rate_up',   as: 'rate_up'
          patch 'rate-down'     => 'posts#rate_down', as: 'rate_down'
        end
      end
    end
  end

  # Suche
  get     "search"                  => 'search#search'

  # Adminbereich
  get     "admin/index"            => 'admins#index',         as: :admins_index
  delete  "admin/destroy/:id"      => 'admins#destroy',       as: :admins_destroy
  patch   "admin/nospam/:id"       => 'admins#noSpam' ,       as: :admins_nospam
  get     "admin/new-posts"        => 'admins#new_posts',     as: :admin_new_posts
  get     "admin/spam-posts"       => 'admins#spam_post',     as: :admin_spam_posts
  get     "admin/topics-threads"   => 'admins#topics_threads',as: :admin_topics_threads
  get     "admin/users"            => 'admins#users',         as: :admin_users
  get     "admin/topics/:id/edit"  => 'admins#topic_edit',    as: :admin_edit_topic
  get     "admin/thread/:id/edit"  => 'admins#thread_edit',   as: :admin_edit_thread
  get     "admin/thread/:id/move"  => 'admins#thread_move',   as: :admin_move_thread
  patch   "admin/thread/:id/moved" => 'admins#thread_moved',  as: :admin_moved_thread

  # User
  get   "user"          => 'user#current_user_profil',          as: 'current_user'
  patch "user"          => 'user#update'
  put   "user"          => 'user#update'
  get   "user/edit"     => 'user#edit',                         as: 'edit_user'
  get   "user/threads"  => 'user#current_user_threads',         as: 'current_user_threads'
  get   "user/messages" => 'user#current_user_messages',        as: 'current_user_messages'
  get   "user/:id"      => 'user#show',                         as: 'show_user'

  # Private Nachrichten
  get   "user/messages/new-message" => 'private_message#new_message',           as: 'private_messages'
  post  "user/messages/new-message" => 'private_message#send_private_message'
  get   "user/messages/:id"         => 'private_message#show',                  as: 'show_private_message'

  # Statische Seiten
  get "/impressum" => "static_pages#impressum" , as: 'impressum'

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def search
    if params[:search_field] == ''
      flash[:search_error] = 'Bitte geben Sie einen Suchbegriff ein!'
      redirect_to root_path
    else
      @postResults    = Post.all.where("title like ? or content like ?","%" + params[:search_field] + "%", "%" + params[:search_field] + "%" )
      @userResults    = User.all.where("email like ?","%" + params[:search_field] + "%")
      @threadResults  = UserThread.all.where("title like ?","%" + params[:search_field] + "%")
      @topicResults   = Topic.all.where("name like ?","%" + params[:search_field] + "%")
    end
  end

end

app/helpers/search_helper.rb
module SearchHelper

  def getPage n
    page = n.user_thread.posts.where("id <= #{n.id}").all.count
    (page/10.0).ceil
  end

  def bootstrap_panel(title, &block)

      content_tag :div, class: 'panel panel-default' do
        content_tag :div, class: 'panel-body' do
          content_tag(:h2, title.to_s.html_safe) +
          content_tag(:div) { yield }
        end
      end

  end

end

app/views/search/search.html.erb
<h1>Suchergebnisse</h1>

<div class="row">
  <div class="col-xs-12 col-sm-6 col-md-8">
    <div class="panel panel-default">
      <div class="panel-body">
        <h2>Posts (<%= @postResults.count %>)</h2>
        <% if @postResults.any? %>
            <table class="table table-striped">
              <tr>
                <th>Post</th>
                <th>Thread</th>
                <th>Topic</th>
              </tr>
              <% @postResults.each do |result| %>
                  <tr>
                    <td><%= link_to result.title, path_to_post(result) %></td>
                    <td><%= link_to result.user_thread.title, topic_user_thread_path(result.topic, result.user_thread) %></td>
                    <td><%= link_to result.topic.name, topic_path(result.topic) %></td>
                  </tr>
              <% end %>
            </table>
        <% else %>
            <p>Kein Post gefunden</p>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-xs-6 col-sm-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <h2>Posts (<%= @postResults.count %>)</h2>
        <% if @postResults.any? %>
            <div class="list-group">
              <% @postResults.each do |result| %>
                  <a href=<%= path_to_post(result) %> class="list-group-item">
                    <h4 class="list-group-item-heading"><%= result.title %></h4>

                    <p class="list-group-item-text"><%= result.content[0..64] %>...</p>
                  </a>
              <% end %>
            </div>

        <% else %>
            <p>Kein Post gefunden</p>
        <% end %>
      </div>
    </div>
  </div>


</div>


<div class="row">
  <div class="col-xs-6 col-sm-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <h2>Topics (<%= @topicResults.count %>)</h2>
        <% if @topicResults.any? %>
            <% @topicResults.each do |result| %>
                <p> <%= link_to result.name, topics_path(result) %>  </p>
            <% end %>
        <% else %>
            <p>Keine Topics gefunden</p>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-xs-6 col-sm-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <h2>Threads (<%= @threadResults.count %>)</h2>
        <% if @threadResults.any? %>
            <% @threadResults.each do |result| %>
                <p> <%= link_to result.title, topic_user_threads_path(result.topic, result) %>  </p>
            <% end %>
        <% else %>
            <p>Keine Threads gefunden</p>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-xs-6 col-sm-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <h2>User (<%= @userResults.count %>)</h2>
        <% if @userResults.any? %>
            <% @userResults.each do |result| %>
                <p> <%= link_to result.email, show_user_path(result) %>  </p>
            <% end %>
        <% else %>
            <p>Keine User gefunden</p>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= link_to "Back", root_path, class: 'btn btn-primary' %>