config/routes.rb
Forum::Application.routes.draw do

  
  root   'topics#index'


  devise_for :users


  resources :topics, except: [:show, :edit] do
    resources :user_threads, except: [:show, :edit] do
      resources :posts, except: [:show, :edit] do
        member do 
          patch 'mark-as-spam'  => 'posts#spam',      as: 'spam'
          patch 'rate-up'       => 'posts#rate_up',   as: 'rate_up'
          patch 'rate-down'     => 'posts#rate_down', as: 'rate_down'
        end
      end
    end
  end

  # Suche
  get     "search"                  => 'search#search'

  # Adminbereich
  get     "admin/index"            => 'admins#index',         as: :admins_index
  delete  "admin/destroy/:id"      => 'admins#destroy',       as: :admins_destroy
  patch   "admin/nospam/:id"       => 'admins#noSpam' ,       as: :admins_nospam
  get     "admin/new-posts"        => 'admins#new_posts',     as: :admin_new_posts
  get     "admin/spam-posts"       => 'admins#spam_post',     as: :admin_spam_posts
  get     "admin/topics-threads"   => 'admins#topics_threads',as: :admin_topics_threads
  get     "admin/users"            => 'admins#users',         as: :admin_users
  get     "admin/topics/:id/edit"  => 'admins#topic_edit',    as: :admin_edit_topic
  get     "admin/thread/:id/edit"  => 'admins#thread_edit',   as: :admin_edit_thread
  get     "admin/thread/:id/move"  => 'admins#thread_move',   as: :admin_move_thread
  patch   "admin/thread/:id/moved" => 'admins#thread_moved',  as: :admin_moved_thread

  # User
  get   "user"          => 'user#current_user_profil',          as: 'current_user'
  patch "user"          => 'user#update'
  put   "user"          => 'user#update'
  get   "user/edit"     => 'user#edit',                         as: 'edit_user'
  get   "user/threads"  => 'user#current_user_threads',         as: 'current_user_threads'
  get   "user/messages" => 'user#current_user_messages',        as: 'current_user_messages'
  get   "user/:id"      => 'user#show',                         as: 'show_user'

  # Private Nachrichten
  get   "user/messages/new-message" => 'private_message#new_message',           as: 'private_messages'
  post  "user/messages/new-message" => 'private_message#send_private_message'
  get   "user/messages/:id"         => 'private_message#show',                  as: 'show_private_message'

  # Statische Seiten
  get "/impressum" => "static_pages#impressum" , as: 'impressum'

end

app/models/post.rb
class Post < ActiveRecord::Base
  	belongs_to :user_thread
  	belongs_to :user
    has_many :rates
    has_one :topic, through: :user_thread
    has_many :upRates, -> { where type: 'UpRate' }, class_name: 'Rate'
    has_many :downRates, ->  { where type: 'DownRate' }, class_name: 'Rate'

  	validates :title,
		presence: true,
		length: { minimum: 4 }

	validates :content,
		presence: true,
		length: { minimum: 1 }


	self.per_page = 10



  def getPage
    page = self.user_thread.posts.where("id <= #{self.id}").all.count
    (page/10.0).ceil
  end

  def postTagId
    "post#{self.id}"
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post_topic
  before_action :set_post_user_thread
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :userCheck

  include PostsHelper


  # GET /posts
  def index
    @posts = @userThread.posts.page(params[:page])
    @post = @userThread.posts.new
  end

  # GET /posts/1
  def show
  end

  # GET /posts/new
  def new
    @post = @userThread.posts.new
  end

  # GET /posts/1/edit
  def edit
  end

  def spam
    post = Post.find(params[:id])
    post.spam = true
    post.save
    redirect_to action: 'index'
  end

  # POST /posts
  def create
    @posts = @userThread.posts.all
    @post = @userThread.posts.new(post_params)
    @post.user = current_user
    

      if @post.save
        redirect_to topic_user_thread_posts_path(@topic,@userThread), notice: 'Post was successfully created.'
      else
        @posts = @userThread.posts.page(params[:page])
        render action: 'index'
      end
  end

  # PATCH/PUT /posts/1
  def update
      if @post.update(post_params)
        redirect_to [@topic, @userThread, @post], notice: 'Post was successfully updated.'
      else
        render action: 'edit'
      end
  end

  # DELETE /posts/1
  def destroy
    if current_user.try(:admin?)
      @post.destroy
    end

    redirect_to topic_user_thread_posts_url
  end

  def rate_up
    if user_signed_in?
      post    = Post.find(params[:id])
      r       = UpRate.new
      r.post  = post
      r.user  = current_user
      r.save
    end

    redirect_to path_to_post post
  end

  def rate_down
    if user_signed_in?
      post    = Post.find(params[:id])
      r       = DownRate.new
      r.post  = post
      r.user  = current_user
      r.save
    end

    redirect_to path_to_post post
  end

  private

    def set_post_topic
      @topic = Topic.find(params[:topic_id])
    end

    def set_post_user_thread
      @userThread = @topic.user_threads.find(params[:user_thread_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = @userThread.posts.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :spam, :user_thread_id, :rating)
    end

    def userCheck
      unless params[:action] == "index"
        unless user_signed_in?
          redirect_to action: 'index'
        end
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper

  def path_to_post(post)
    topic_user_thread_posts_path(post.topic, post.user_thread, anchor: post.postTagId, page: post.getPage)
  end

end

app/views/posts/_addPost.html.erb
<% if user_signed_in? %>
<div id="addPost">
	<%= render partial: "form" %>
</div>
<% end %>

app/views/posts/_delete.html.erb
<% if current_user.try(:admin?) %> 
<%= link_to topic_user_thread_post_path(post.user_thread.topic,post.user_thread,post), method: "delete" do%>
<i class="icon-trash pull-right"> </i>
<% end %>
<% end %>

app/views/posts/_form.html.erb
<%= render partial: "layouts/error", locals: { errors: @post.errors } %>

<%= form_for [@topic, @userThread, @post] do |f| %>

    <div class = "panel panel-default" >

      <div class="panel-heading">
        <%= f.text_field :title %>
      </div>

      <div class="panel-body">
        <div class="col-xs-4 col-sm-2">
          <%= link_to show_user_path(current_user) do %>
              <%= image_tag current_user.avatar, class: "img-rounded" %>
          <% end %>
        </div>

        <div class="col-xs-12 col-sm-6 col-md-8">
            <%= f.text_area :content, rows: 6, cols: 105 %>
        </div>

      </div>

      <div class="panel-footer">
        <%= current_user.signature %>

        <%= f.submit class: 'btn btn-success pull-right'%>
      </div>

    </div>

<% end %>

app/views/posts/_post.html.erb
<div class = "panel panel-default" id= <%= "post" + post.id.to_s %> >

  <div class="panel-heading">
    <h3><%= word_wrap post.title %></h3>
  </div>

  <div class="panel-body">
    <div class="col-xs-4 col-sm-2">
      <% unless post.user.nil? %>
          <%= link_to show_user_path(post.user) do %>
              <%= image_tag post.user.avatar, class: "img-rounded" %>
          <% end %>
      <% else %>
          <p class="pull-right"> geloeschter User </p>
      <% end %>
    </div>

    <div class="col-xs-12 col-sm-6 col-md-8">
      <%= word_wrap post.content, line_width: 90 %>
    </div>

  </div>

  <div class="panel-footer">
    <% unless post.user.nil? %>
        <%= post.user.signature %>
    <% end %>
    <%= render partial: "rating", locals: {post: post} %>
    <%= render partial: "spam", locals: {post: post} %>
    <%= render partial: "delete", locals: {post: post} %>
  </div>

</div>

app/views/posts/_rating.html.erb
<% if user_signed_in? %>
    <p class="text-success pull-right"> <%= post.upRates.count %> </p>

    <%= link_to rate_up_topic_user_thread_post_path(@topic, @userThread, post), method: :patch  do %>
        <span class="glyphicon glyphicon-thumbs-up pull-right"> </span>
    <% end %>

    <p class="text pull-right"> <%= post.downRates.count  %> </p>

    <%= link_to  rate_down_topic_user_thread_post_path(@topic, @userThread, post), method: :patch do %>
        <span class="glyphicon glyphicon-thumbs-down pull-right"> </span>
    <% end %>

<% end %>

app/views/posts/_spam.html.erb
<% if user_signed_in? %>
    <% unless post.spam %>
        <%= link_to spam_topic_user_thread_post_path(@topic, @userThread, post), method: :patch  do %>

            <span class="glyphicon glyphicon-flag pull-right"> </span>
            <% end %>
    <% else %>
        <span class="label label-important">Post wurde als Spam gekennzeichnet</span>
    <% end %>
<% end %>

app/views/posts/index.html.erb
<h1><%= @userThread.title %></h1>

<div id="containerAll" >

	<%= will_paginate %>
	<%= render @posts %>
	<%= will_paginate %>

	<%= render partial: "addPost" %>
</div>

<%= link_to "Back" , topic_user_threads_path(@topic) %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', topic_user_thread_posts_path(@topic, @userThread) %>