config/routes.rb
Forum::Application.routes.draw do

  
  root   'topics#index'


  devise_for :users


  resources :topics, except: [:show, :edit] do
    resources :user_threads, except: [:show, :edit] do
      resources :posts, except: [:show, :edit] do
        member do 
          patch 'mark-as-spam'  => 'posts#spam',      as: 'spam'
          patch 'rate-up'       => 'posts#rate_up',   as: 'rate_up'
          patch 'rate-down'     => 'posts#rate_down', as: 'rate_down'
        end
      end
    end
  end

  # Suche
  get     "search"                  => 'search#search'

  # Adminbereich
  get     "admin/index"            => 'admins#index',         as: :admins_index
  delete  "admin/destroy/:id"      => 'admins#destroy',       as: :admins_destroy
  patch   "admin/nospam/:id"       => 'admins#noSpam' ,       as: :admins_nospam
  get     "admin/new-posts"        => 'admins#new_posts',     as: :admin_new_posts
  get     "admin/spam-posts"       => 'admins#spam_post',     as: :admin_spam_posts
  get     "admin/topics-threads"   => 'admins#topics_threads',as: :admin_topics_threads
  get     "admin/users"            => 'admins#users',         as: :admin_users
  get     "admin/topics/:id/edit"  => 'admins#topic_edit',    as: :admin_edit_topic
  get     "admin/thread/:id/edit"  => 'admins#thread_edit',   as: :admin_edit_thread
  get     "admin/thread/:id/move"  => 'admins#thread_move',   as: :admin_move_thread
  patch   "admin/thread/:id/moved" => 'admins#thread_moved',  as: :admin_moved_thread

  # User
  get   "user"          => 'user#current_user_profil',          as: 'current_user'
  patch "user"          => 'user#update'
  put   "user"          => 'user#update'
  get   "user/edit"     => 'user#edit',                         as: 'edit_user'
  get   "user/threads"  => 'user#current_user_threads',         as: 'current_user_threads'
  get   "user/messages" => 'user#current_user_messages',        as: 'current_user_messages'
  get   "user/:id"      => 'user#show',                         as: 'show_user'

  # Private Nachrichten
  get   "user/messages/new-message" => 'private_message#new_message',           as: 'private_messages'
  post  "user/messages/new-message" => 'private_message#send_private_message'
  get   "user/messages/:id"         => 'private_message#show',                  as: 'show_private_message'

  # Statische Seiten
  get "/impressum" => "static_pages#impressum" , as: 'impressum'

end

app/views/layouts/_error.html.erb
<% if errors.any? %>
    <div class="alert alert-danger" id="error_explanation">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <strong><%= pluralize(errors.count, "error") %> prohibited this from being saved:</strong>

      <ul>
        <% errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<div id="footer">
 <nav class="navbar navbar-default">
   <ul class="nav navbar-nav">
     <li>
       <%= link_to "Impressum", impressum_path %>
     </li>

     <li>
       <% if current_user.try(:admin?) %>
           <%= link_to 'Admin' , admins_index_path, class: "headerLink" %>
       <% end %>
     </li>

   </ul>
 </nav>
</div>

app/views/layouts/_header.html.erb
<div id="mainHeader">
  <nav class="navbar navbar-default" role="navigation">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Forum', root_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="mainHeader_navbar">

      <ul class="nav navbar-nav">
        <li>
          <%= render partial: "layouts/login" %>
        </li>
      </ul>

      <ul class="nav pull-right">
        <li>
          <%= render partial: "layouts/search" %>
        </li>
      </ul>
    </div>

  </nav>
</div>

app/views/layouts/_login.html.erb
<% unless user_signed_in? %>
    <li>
      <%= link_to 'Login', new_user_session_path %>
    </li>
<% else %>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">User <b class="caret"></b></a>
      <ul class="dropdown-menu">
        <li>
          <%= link_to 'Profil', current_user_path %>
        </li>

        <li>
          <%= link_to 'Logout', destroy_user_session_path, :method => :delete %>
        </li>
      </ul>
    </li>
<% end %>

app/views/layouts/_search.html.erb
<%= form_tag("/search",method: :get, class: "navbar-form navbar-right") do |f| %>
    <div class="input-group">

      <% if flash[:search_error] %>
          <%= label_tag 'error_label', flash[:search_error], for: 'search_field' %>
      <% end %>

      <div class="form-group">
        <%= text_field_tag :search_field, nil, class: 'form-control', placeholder: 'Search' %>
      </div>

      <%= submit_tag "Search", class: 'btn btn-default' %>
    </div>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>
      <% if @title.nil? %>
        <%= "Admin" %>
      <% else %>
        <%= "Admin - #{@title}" %>
      <% end %>
    </title>
	<%= stylesheet_link_tag    "admin", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "admin", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
</head>
<body>
    <%= render partial: "admins/menue" %>
	<div id="mainContent" class="container">
		<%= yield %>
	</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= @tile ||= "Forum" %></title>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
        <%= render partial: "layouts/header" %>

        <% if content_for?(:user_profil) %>
            <%= yield(:user_profil) %>
          <% else %>
            <%= yield %>
          <% end %>

        <%= render partial: "layouts/footer" %>
	</div>
</div>
</body>
</html>

app/views/layouts/user.html.erb
<% content_for :user_profil do %>
    <div class="row">
      <div class="col-md-2">
        <ul class="nav nav-pills nav-stacked">

          <% if @active_link == 1 %>
              <li class="active">
          <% else %>
              <li>
          <% end %>
          <% if @user == current_user %>
            <%= link_to 'Profile', current_user_path %>
          <% else %>
            <%= link_to 'Profile', show_user_path( User.find(params[:id]) ) %>
          <% end %>
          </li>

          <% if @user == current_user %>
              <% if @active_link == 2 %>
                  <li class="active">
              <% else %>
                  <li>
              <% end %>
              <%= link_to 'My Threads', current_user_threads_path %>
              </li>

              <% if @active_link == 3 %>
                  <li class="active">
              <% else %>
                  <li>
              <% end %>
              <%= link_to current_user_messages_path do %>
                  <span class="badge pull-right"><%= @new_message_count %></span>
                  Messages
              <% end %>
              </li>
          <% end %>

        </ul>
      </div>

      <div class="col-md-10">
        <%= yield %>
      </div>
    </div>
<% end %>

<%= render template: "layouts/application" %>